# Generated by Django 5.1.4 on 2025-01-02 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookroute', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='bookroute/picture/', verbose_name='写真'),
        ),
    ]
